// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs_d0QXEKl9rQOYSJ7qu-TAlX8QqzUxWg',
    appId: '1:142082217671:android:f16d9679ad9989378910e2',
    messagingSenderId: '142082217671',
    projectId: 'al-waha-32035',
    storageBucket: 'al-waha-32035.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQmxBYOtJOYTZTXfyrj8DvaCjqJqmdNPE',
    appId: '1:142082217671:ios:848786b133ff4d508910e2',
    messagingSenderId: '142082217671',
    projectId: 'al-waha-32035',
    storageBucket: 'al-waha-32035.appspot.com',
    androidClientId: '142082217671-21p3ehfh92daintgirvthbd96tu7mghf.apps.googleusercontent.com',
    iosClientId: '142082217671-hqtq7p50kse8vpk556d9vfecjf3d9g2i.apps.googleusercontent.com',
    iosBundleId: 'com.example.alWaha',
  );
}
